name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        with:
          node-version: 10.x
          yarn-version: 1.19.x
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: web-build # The folder the action should deploy.
          BUILD_SCRIPT: yarn install && yarn build:web && yarn resolve-paths:web # The build script the action should run prior to deploying.
