name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        yarn-version: 1.19.x
    - name: yarn install, yarn deploy-pages:web
      run: |
        yarn install
        yarn deploy-pages:web
      env:
        CI: true
